services:
  - type: web
    name: aromatik3
    runtime: node
    rootDir: Aromatik3
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
